ASP_NET/Models/Forum/ForumIndexModel.cs
namespace ASP_NET.Models.Forum;

public class ForumIndexModel
{
    public Boolean UserCanCreate { get; set; }
    public List<ForumSectionModel> Sections { get; set; } = null!;
    public String? CreateMessage { get; set; }
    
    public Boolean? IsMessagePositive { get; set; }
    public ForumSectionFormModel? FormModel { get; set; }

}

ASP_NET/Models/Forum/ForumPostFormModel.cs
using Microsoft.AspNetCore.Mvc;

namespace ASP_NET.Models.Forum;

public class ForumPostFormModel
{
    [FromForm(Name = "post-content")] 
    public String Content { get; set; } = null!;
    
    [FromForm(Name = "topic-id")]
    public String TopicId { get; set; } = null!;
    
    [FromForm(Name = "reply-id")]
    public String? ReplyId { get; set; }
    
}

ASP_NET/Models/Forum/ForumPostViewModel.cs
namespace ASP_NET.Models.Forum;

public class ForumPostViewModel
{
    public String Id { get; set; } = null!;
    public String Content { get; set; } = null!;
    public String CreatedDtString { get; set; } = null!;
    public String AuthorAvatar { get; set; } = null!;
    public String AuthorName { get; set; } = null!;
    public String? ReplyPreview { get; set; }
}

ASP_NET/Models/Forum/ForumSectionFormModel.cs
using Microsoft.AspNetCore.Mvc;

namespace ASP_NET.Models.Forum;

public class ForumSectionFormModel
{
    [FromForm(Name = "section-title")]
    public String Title { get; set; } = null!;
    [FromForm(Name = "section-description")]
    public String Description { get; set; } = null!;
    [FromForm(Name = "section-logo")]
    public IFormFile Logo { get; set; } = null!;

}

ASP_NET/Models/Forum/ForumSectionModel.cs
namespace ASP_NET.Models.Forum;

public class ForumSectionModel
{
    public String UrlIdString { get; set; } = null!;
    public String Title { get; set; } = null!;
    public String Description { get; set; } = null!;
    public String Logo { get; set; } = null!;
    public String CreatedDtString { get; set; } = null!;
    public String AuthorName { get; set; } = null!;
    public String? AuthorAvatar { get; set; } = null!;
    public String AuthorLogin { get; set; } = null!;
    
    public int LikesCount { get; set; }
    public int DislikesCount { get; set; }
    
    public int? GivenRate { get; set; }
    public int Sights { get; set; }
}

ASP_NET/Models/Forum/ForumSectionsModel.cs
namespace ASP_NET.Models.Forum;

public class ForumSectionsModel
{
    public Boolean UserCanCreate { get; set; }
    public List<ForumThemeModel> Themes { get; set; } = null!;
    public String? CreateMessage { get; set; }
    
    public Boolean? IsMessagePositive { get; set; }
    
    public ForumThemeFormModel? FormModel { get; set; }
}

ASP_NET/Models/Forum/ForumThemeFormModel.cs
using Microsoft.AspNetCore.Mvc;

namespace ASP_NET.Models.Forum;

public class ForumThemeFormModel
{
    [FromForm(Name = "theme-title")]
    public String Title { get; set; } = null!;
    [FromForm(Name = "theme-description")]
    public String Description { get; set; } = null!;
    [FromForm(Name = "section-id")]
    public String SectionId { get; set; } = null!;
}

ASP_NET/Models/Forum/ForumThemeModel.cs
namespace ASP_NET.Models.Forum;

public class ForumThemeModel
{
    public String UrlIdString { get; set; } = null!;
    public String Title { get; set; } = null!;
    public String Description { get; set; } = null!;
    public String CreatedDtString { get; set; } = null!;
    public DateTime CreatedDt { get; set; }
    public String AuthorName { get; set; } = null!;
    public String? AuthorAvatar { get; set; } = null!;
    public String AuthorRegisterDtString { get; set; } = null!;
}

ASP_NET/Models/Forum/ForumThemesPageModel.cs
namespace ASP_NET.Models.Forum;

public class ForumThemesPageModel
{
    public Boolean UserCanCreate { get; set; }
    public List<ForumTopicViewModel> Topics { get; set; } = null!;
    public String Title { get; set; } = null!;
    public String ThemeIdString { get; set; } = null!;
    
    
    public String? CreateMessage { get; set; }
    public Boolean? IsMessagePositive { get; set; }
    public ForumTopicFormModel? FormModel { get; set; }
}

ASP_NET/Models/Forum/ForumTopicFormModel.cs
using Microsoft.AspNetCore.Mvc;

namespace ASP_NET.Models.Forum;

public class ForumTopicFormModel
{
    [FromForm(Name = "topic-title")]
    public String Title { get; set; } = null!;
    [FromForm(Name = "topic-description")]
    public String Description { get; set; } = null!;
    [FromForm(Name = "theme-id")]
    public String ThemeId { get; set; } = null!;
}

ASP_NET/Models/Forum/ForumTopicViewModel.cs
namespace ASP_NET.Models.Forum;

public class ForumTopicViewModel
{
    public String UrlIdString { get; set; } = null!;
    public String Title { get; set; } = null!;
    public String Description { get; set; } = null!;
    public String CreatedDtString { get; set; } = null!;
    public String AuthorName { get; set; } = null!;
}

ASP_NET/Models/Forum/ForumTopicsPageModel.cs
namespace ASP_NET.Models.Forum;

public class ForumTopicsPageModel
{
    public Boolean UserCanCreate { get; set; }
    public List<ForumPostViewModel> Posts { get; set; } = null!;
    public String Title { get; set; } = null!;
    public String Description { get; set; } = null!;
    public String TopicIdString { get; set; } = null!;
    
    
    public String? CreateMessage { get; set; }
    public Boolean? IsMessagePositive { get; set; }
    public ForumPostFormModel? FormModel { get; set; }
}

ASP_NET/Controllers/ForumController.cs
using System.Security.Claims;
using Microsoft.AspNetCore.Mvc;
using ASP_NET.Data;
using ASP_NET.Data.Entity;
using ASP_NET.Models.Forum;
using ASP_NET.Services.Display;
using ASP_NET.Services.Random;
using ASP_NET.Services.Validation;
using Microsoft.AspNetCore.Mvc.ModelBinding.Validation;
using Microsoft.EntityFrameworkCore;

namespace ASP_NET.Controllers;

public class ForumController : Controller
{
    private readonly DataContext _dataContext;
    private readonly ILogger<ForumController> _logger;
    private readonly IValidationService _validationService;
    private readonly IDisplayService _displayService;
    private readonly IRandomService _randomService;
    private int Counter
    {
        get => _counter++;
        set { _counter = value; }
    }

    private int _counter;

    public ForumController(DataContext dataContext, ILogger<ForumController> logger, IValidationService validationService, IDisplayService displayService, IRandomService randomService)
    {
        _dataContext = dataContext;
        _logger = logger;
        _validationService = validationService;
        _displayService = displayService;
        _randomService = randomService;
        _counter = 0;
    }

    // GET
    public IActionResult Index()
    {
        Counter = 0;
        String? userId = HttpContext.User.Claims
            .FirstOrDefault(c => c.Type == ClaimTypes.Sid)?.Value;
        ForumIndexModel model = new()
        {
            UserCanCreate = HttpContext.User.Identity?.IsAuthenticated == true,
            Sections = _dataContext.Sections
                .Include(s => s.Author)
                .Include(s => s.RateList)
                .OrderBy(s => s.CreatedDt)
                .AsEnumerable()
                .Select(s => new ForumSectionModel()
            {
                UrlIdString = s.Id.ToString(),
                Title = s.Title,
                Description = s.Description,
                Logo = $"/imgs/logos/{(s.Logo is null ? "section" + Counter.ToString() + ".png" : s.Logo)}",
                CreatedDtString = DateTime.Today == s.CreatedDt.Date ? 
                    "Today " + s.CreatedDt.ToString("HH:mm") 
                    : s.CreatedDt.ToString("dd.MM.yyyy HH:mm"),
                AuthorName = s.Author.RealName,
                AuthorAvatar = s.Author.Avatar is null ? null : $"/avatars/{s.Author.Avatar}",
                AuthorLogin = s.Author.Login,
                LikesCount = s.RateList.Count(r => r.Rating > 0),
                DislikesCount = s.RateList.Count(r => r.Rating < 0),
                GivenRate = userId == null ? null
                    : s.RateList.FirstOrDefault(r => r.UserId == Guid.Parse(userId))?.Rating,
            }).ToList(),
        };
        foreach (var section in model.Sections)
        {
            section.Sights = _dataContext.Sights.AsEnumerable().Count(st => st.ItemId == Guid.Parse(section.UrlIdString));

        }
        if (HttpContext.Session.GetString("CreateMessage") is String message)
        {
            model.CreateMessage = message;
            model.IsMessagePositive = HttpContext.Session.GetInt32("IsMessagePositive") != 0;

            if (model.IsMessagePositive == false)
            {
                model.FormModel = new()
                {
                    Title = HttpContext.Session.GetString("SectionTitle")!,
                    Description = HttpContext.Session.GetString("SectionDescription")!
                };
                HttpContext.Session.Remove("SectionTitle");
                HttpContext.Session.Remove("SectionDescription");
            }

            HttpContext.Session.Remove("CreateMessage");
            HttpContext.Session.Remove("IsMessagePositive");
        }
        return View(model);
    }
    
    
    
    [HttpPost]
    public RedirectToActionResult CreateSection([FromForm] ForumSectionFormModel model)
    {
        _logger.LogInformation("Title: {t}, Description: {d}", model.Title, model.Description);
        if (!_validationService.Validate(model.Title, ValidationTerms.NotEmpty)
            || !_validationService.Validate(model.Description, ValidationTerms.NotEmpty))
        {
            HttpContext.Session.SetString("CreateMessage" ,"Title cannot be empty");
            HttpContext.Session.SetInt32("IsMessagePositive", 0);
            HttpContext.Session.SetString("SectionTitle", model.Title ?? String.Empty);
            HttpContext.Session.SetString("SectionDescription", model.Description ?? String.Empty);

        }
        else
        {
            Guid userId;
            try
            {
                userId = Guid.Parse(HttpContext.User.Claims.FirstOrDefault(c => c.Type == ClaimTypes.Sid)?.Value!);
                Section section = new()
                {
                    Id = Guid.NewGuid(),
                    AuthorId = userId,
                    Title = model.Title,
                    Description = model.Description,
                    CreatedDt = DateTime.Now,
                };
                if (model.Logo is not null)
                {
                    String ext = Path.GetExtension((model.Logo.FileName));
                    String name = _randomService.RandomFileName(16);
                    String logoFilename = name + ext;
                    string path = "wwwroot/imgs/logos/" + logoFilename;
                    using (var fileStream = new FileStream(
                               path,
                               FileMode.Create))
                    {
                        model.Logo.CopyTo(fileStream);
                        section.Logo = logoFilename;
                    }

                }

                _dataContext.Sections.Add(section);
                
                _dataContext.SaveChanges();
                HttpContext.Session.SetString("CreateMessage" ,"Section successfully created");
                HttpContext.Session.SetInt32("IsMessagePositive", 1);
            }
            catch
            {
                HttpContext.Session.SetString("CreateMessage" ,"Auth error");
                HttpContext.Session.SetInt32("IsMessagePositive", 0);
                HttpContext.Session.SetString("SectionTitle", model.Title ?? String.Empty);
                HttpContext.Session.SetString("SectionDescription", model.Description ?? String.Empty);
            }
        }
        return RedirectToAction(nameof(Index));
    }

    public IActionResult Sections([FromRoute] String id)
    {
        ViewData["SectionId"] = id;
        _dataContext.Sights.Add((new()
        {
            Id = Guid.NewGuid(),
            Moment = DateTime.Now,
            ItemId = Guid.Parse(id),
            UserId = null
        }));
        _dataContext.SaveChanges();
        ForumSectionsModel model = new()
        {
            UserCanCreate = HttpContext.User.Identity?.IsAuthenticated == true,
            Themes = _dataContext.Themes
                .Include(t => t.Author)
                .Where(t => t.SectionId == Guid.Parse(id))
                .Select(t => new ForumThemeModel()
                {
                    Title = t.Title,
                    Description = t.Description,
                    UrlIdString = t.Id.ToString(),
                    CreatedDtString = DateTime.Today == t.CreatedDt.Date ? 
                        "Today " + t.CreatedDt.ToString("HH:mm") 
                        : t.CreatedDt.ToString("dd.MM.yyyy HH:mm"),
                    AuthorAvatar = $"/avatars/{t.Author.Avatar ?? "no-avatar.png"}",
                    AuthorName = t.Author.IsRealNamePublic ? t.Author.RealName : t.Author.Login,
                    CreatedDt = t.CreatedDt,
                    AuthorRegisterDtString = t.Author.RegisterDt.Date.ToString()
                })
                .ToList()
        };
        if (HttpContext.Session.GetString("CreateMessage") is String message)
        {
            model.CreateMessage = message;
            model.IsMessagePositive = HttpContext.Session.GetInt32("IsMessagePositive") != 0;

            if (model.IsMessagePositive == false)
            {
                model.FormModel = new()
                {
                    Title = HttpContext.Session.GetString("ThemeTitle")!,
                    Description = HttpContext.Session.GetString("ThemeDescription")!
                };
                HttpContext.Session.Remove("ThemeTitle");
                HttpContext.Session.Remove("ThemeDescription");
            }

            HttpContext.Session.Remove("CreateMessage");
            HttpContext.Session.Remove("IsMessagePositive");
        }
        return View(model);
    }

    [HttpPost]
    public RedirectToActionResult CreateTheme([FromForm] ForumThemeFormModel model)
    {
        _logger.LogInformation("Title: {t}, Description: {d}", model.Title, model.Description);
        if (!_validationService.Validate(model.Title, ValidationTerms.NotEmpty)
            || !_validationService.Validate(model.Description, ValidationTerms.NotEmpty))
        {
            HttpContext.Session.SetString("CreateMessage" ,"Title cannot be empty");
            HttpContext.Session.SetInt32("IsMessagePositive", 0);
            HttpContext.Session.SetString("ThemeTitle", model.Title ?? String.Empty);
            HttpContext.Session.SetString("ThemeDescription", model.Description ?? String.Empty);

        }
        else
        {
            Guid userId;
            try
            {
                userId = Guid.Parse(HttpContext.User.Claims.FirstOrDefault(c => c.Type == ClaimTypes.Sid)?.Value!);
                _dataContext.Themes.Add(new()
                {
                    Id = Guid.NewGuid(),
                    AuthorId = userId,
                    Title = model.Title,
                    Description = model.Description,
                    CreatedDt = DateTime.Now,
                    SectionId = Guid.Parse(model.SectionId)
                });
                
                _dataContext.SaveChanges();

ASP_NET/Views/Forum/DisplayTemplates/PostTemplate.cshtml
@model ASP_NET.Models.Forum.ForumPostViewModel
<div class="media g-mb-30 media-comment row">
  <div class="col col-1">
    <img class="d-flex g-w-100 rounded-circle g-mt-3 g-mr-15" src="@Model.AuthorAvatar" alt="ava">
  </div>
  <div class="media-body u-shadow-v18 g-bg-secondary g-pa-30 col col-11">
    <div class="g-mb-15">
      <h5 class="h5 g-color-gray-dark-v1 mb-0">@Model.AuthorName</h5>
      <span class="g-color-gray-dark-v4 g-font-size-12">@Model.CreatedDtString</span>
    </div>

    <p>
      @Html.Raw(Model.Content.Replace("\n", "<br />"))
    </p>

    <ul class="list-inline d-flex my-0">
      <li class="list-inline-item g-mr-20">
        <a class="u-link-v5 g-color-gray-dark-v4 g-color-primary--hover" href="#!">
          <i class="bi-hand-thumbs-up-fill g-pos-rel g-top-1 g-mr-3"></i>
          178
        </a>
      </li>
      <li class="list-inline-item g-mr-20">
        <a class="u-link-v5 g-color-gray-dark-v4 g-color-primary--hover" href="#!">
          <i class="bi-hand-thumbs-down-fill g-pos-rel g-top-1 g-mr-3"></i>
          34
        </a>
      </li>
      @if (Context.User.Identity is not null 
           && Context.User.Identity.IsAuthenticated)
      {
        <li class="list-inline-item ms-auto">
          <button id="reply-button" class="bi-reply-fill btn g-pos-rel g-top-1 g-mr-3">Reply</button>
        </li>
      }
    </ul>
  </div>
</div>

<script>
  document.addEventListener("DOMContentLoaded", () => {
    const replyButton = document.getElementById("reply-button");
    if (!replyButton) throw "reply-button not found" ;
      replyButton.addEventListener("click", replyClick);
    });
  function replyClick(){
    document.getElementById("post-content").value = "Reply to:\n----------\n@(Model.Content[..30])\n----------\n\n";
    document.getElementById("reply-id-input").value = "@Model.Id";
    }
</script>

ASP_NET/Views/Forum/DisplayTemplates/Section.cshtml
@model ASP_NET.Models.Forum.ForumSectionModel

<div class="card mb-3">
  <div class="row g-0">
    <div class="col-md-3">
      <img src="@Model.Logo" class="img-fluid rounded-start" alt="...">
    </div>
    <div class="col-md-9 d-flex flex-column">
      <div class="card-body">
        <a asp-controller="Forum" asp-action="Sections" asp-route-id="@Model.UrlIdString">
        <h5 class="card-title">@Model.Title</h5>
        </a>
        <p class="card-text">@Model.Description</p>
      </div>
      <div class="card-footer d-flex align-items-center">
        Started: @Model.CreatedDtString 
        @if (Model.AuthorAvatar is not null)
        {
          <img style="max-width: 50px; max-height: 50px" src="@Model.AuthorAvatar" alt="ava"/>
        }
        <a asp-controller="User" asp-action="Profile" asp-route-id="@Model.AuthorLogin">@Model.AuthorName</a>
        <span class="u-link-v5 g-color-gray-dark-v4 mx-3" role="button"
              data-rate="@Model.UrlIdString" data-rate-value="1"
              data-rate-given="@(Model.GivenRate == 1)">
          @if (Model.GivenRate == 1)
          {
            <i class="bi-hand-thumbs-up-fill"></i>
          }
          else
          {
            <i class="bi-hand-thumbs-up"></i>
          }
          @Model.LikesCount
        </span>
        <span class="u-link-v5 g-color-gray-dark-v4 mx-3" role="button" 
              data-rate="@Model.UrlIdString" data-rate-value="-1"
              data-rate-given="@(Model.GivenRate == -1)">
          @if (Model.GivenRate == -1)
          {
            <i class="bi-hand-thumbs-down-fill"></i>
          }
          else
          {
            <i class="bi-hand-thumbs-down"></i>
          }          
          @Model.DislikesCount
        </span>
        
        <span class="mx-3">
          <i class="bi bi-eyeglasses"></i>
          @Model.Sights
        </span>
      </div>
    </div>
    
  </div>
</div>

ASP_NET/Views/Forum/DisplayTemplates/ThemeTemplate.cshtml
@using System.Runtime.InteropServices.JavaScript
@using System.Net.Mime
@model ASP_NET.Models.Forum.ForumThemeModel
@{
    DateTime dateTimeNow = DateTime.Now;
    String createdDtStr = "";
    if (Model.CreatedDt.Date == dateTimeNow.Date)
    {
        createdDtStr = "Today";
    }
    else
    {
        createdDtStr = (dateTimeNow.Date - Model.CreatedDt).Days.ToString() + "day(s) ago";
    }
}
<div class="container-fluid mt-100">
    <div class="row">
        <div class="col-md-12">
            <div class="card mb-5">
                <div class="card-header">
                    <div class="media d-flex align-items-center">
                        <img src="@Model.AuthorAvatar" class="d-block ui-w-40 rounded-circle mx-2" alt="">
                        <div class="media-body mx-2">
                            <a href="javascript:void(0)" data-abc="true">@Model.AuthorName</a>
                            <div class="text-muted small">
                                @createdDtStr
                            </div>
                        </div>
                        <div class="text-muted small mx-2 ms-auto ">
                            <div>Member since <strong>@Model.AuthorRegisterDtString</strong></div>
                            <div><strong>134</strong> posts</div>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    <h5>@Model.Title</h5>
                    <p>
                        @Model.Description
                    </p>
                </div>
                <div class="card-footer d-flex flex-wrap justify-content-between align-items-center p-1">
                    <div class="px-4"> <a href="javascript:void(0)" class="text-muted d-inline-flex align-items-center align-middle" data-abc="true"> <i class="fa fa-heart text-danger"></i>&nbsp; <span class="align-middle">445</span> </a> <span class="text-muted d-inline-flex align-items-center align-middle ml-4"> <i class="fa fa-eye text-muted fsize-3"></i>&nbsp; <span class="align-middle">14532</span> </span> </div>
                    <div class="px-4"> <a asp-action="Themes" asp-route-id="@Model.UrlIdString" class="btn btn-primary"><i class="bi bi-arrow-right-square"></i>&nbsp; See</a> </div>
                </div>
            </div>
        </div>
    </div>
</div>

ASP_NET/Views/Forum/DisplayTemplates/TopicTemplate.cshtml
@model ASP_NET.Models.Forum.ForumTopicViewModel

<div class="col">
    <div class="card h-100">
        <div class="card-header">
            <div class="media d-flex align-items-center">
                @Model.Title
                <div class="media-body mx-2 ms-auto">
                    <a href="javascript:void(0)" data-abc="true">@Model.AuthorName</a>
                    <div class="text-muted small">
                        @Model.CreatedDtString
                    </div>
                </div>
            </div>
        </div>
        <div class="card-body">
            <h5 class="card-title">@Model.Title</h5>
            <p class="card-text">@Model.Description</p>
        </div>
        <a class="float-end" asp-action="Topics" asp-route-id="@Model.UrlIdString">Go to discussion</a>
    </div>
</div>